// Generated by RPG Maker MZ
// Plugin configuration file
// =============================================================================
// IMPORTANT: Add VisuStella plugins from the Sample Project in this order:
// 1. VisuMZ_0_CoreEngine.js
// 2. VisuMZ_1_VisualParallaxes.js (after purchasing from itch.io)
// 3. Other VisuStella plugins as needed
// =============================================================================

var $plugins = [
    // VisuStella Core Engine - REQUIRED (from VisuStella Sample Project)
    // Download from: https://visustella.itch.io/visumz-sample
    // After downloading, copy VisuMZ_0_CoreEngine.js to js/plugins/ folder
    // Then uncomment the entry below:
    /*
    {
        "name": "VisuMZ_0_CoreEngine",
        "status": true,
        "description": "VisuStella MZ - Core Engine",
        "parameters": {}
    },
    */

    // VisuStella Visual Parallaxes - REQUIRED for 2.5D effect
    // Purchase from: https://visustellamz.itch.io/visual-parallaxes
    // After purchasing, copy VisuMZ_1_VisualParallaxes.js to js/plugins/ folder
    // Then uncomment the entry below:
    /*
    {
        "name": "VisuMZ_1_VisualParallaxes",
        "status": true,
        "description": "VisuStella MZ - Visual Parallaxes",
        "parameters": {}
    },
    */
];
