// Generated by RPG Maker MZ
// Plugin configuration file for พจนภัยในดินแดนอันตราย (Peril in the Dangerous Lands)
// =============================================================================
//
// PLUGIN INSTALLATION STATUS:
//
// [ ] VisuMZ_0_CoreEngine.js - Download FREE from:
//     https://visustella.itch.io/visumz-sample
//
// [ ] VisuMZ_1_VisualParallaxes.js - Purchase ($8+) from:
//     https://visustellamz.itch.io/visual-parallaxes
//
// INSTRUCTIONS:
// 1. Download/purchase both plugins from the URLs above
// 2. Copy the .js files to the js/plugins/ folder
// 3. Uncomment the plugin entries below (remove /* and */)
// 4. Open in RPG Maker MZ and verify in Plugin Manager
// 5. Press F5 to playtest - check console for errors
//
// See VISUSTELLA_SETUP.md for detailed installation guide.
//
// =============================================================================

var $plugins = [
    // =========================================================================
    // VisuStella Core Engine - REQUIRED (Must be FIRST)
    // =========================================================================
    // Download from: https://visustella.itch.io/visumz-sample
    // After downloading, copy VisuMZ_0_CoreEngine.js to js/plugins/
    // Then uncomment the entry below:
    /*
    {
        "name": "VisuMZ_0_CoreEngine",
        "status": true,
        "description": "VisuStella MZ - Core Engine v1.82",
        "parameters": {
            "QoL Settings": "",
            "DigitGroupingStandardText": "true",
            "DigitGroupingExText": "true",
            "DigitGroupingDamageSprites": "true",
            "DigitGroupingGaugeSprites": "true",
            "DigitGroupingLocale": "en-US"
        }
    },
    */

    // =========================================================================
    // VisuStella Visual Parallaxes - REQUIRED for 2.5D Effect
    // =========================================================================
    // Purchase from: https://visustellamz.itch.io/visual-parallaxes ($8+)
    // After purchasing, copy VisuMZ_1_VisualParallaxes.js to js/plugins/
    // Then uncomment the entry below:
    /*
    {
        "name": "VisuMZ_1_VisualParallaxes",
        "status": true,
        "description": "VisuStella MZ - Visual Parallaxes v1.07",
        "parameters": {
            "WaterReflections": "",
            "AmpReflections": "true",
            "BlurReflections": "true",
            "DefaultReflections": "true",
            "GroundReflections": "true",
            "OpacityFlat": "30",
            "Top": "0",
            "SolidReflections": "",
            "DefaultSolidReflections": "false",
            "SolidReflectionTop": "0",
            "SolidReflectionBlur": "true",
            "SolidReflectionOpacity": "50"
        }
    },
    */
];

// =============================================================================
// NOTES:
// - Plugin load order is CRITICAL: CoreEngine MUST be before Visual Parallaxes
// - Both plugins must be in the js/plugins/ folder before uncommenting
// - After uncommenting, verify in RPG Maker MZ: Tools → Plugin Manager
// - Test with F5 playtest - check F8 console for any errors
// =============================================================================
